### ISSUE TITLE
Better support for jekyll --watch

### ISSUE THREAD

**Issue by imathis** [octopress/ink#26]

**Comment by mdotasia** [comment]
I'm using a rake task to build a Jekyll site based on ink. The rake task uses `watch` and `serving`options.
since rc.40 Jekyll does not find layouts provided by an ink plugin when an automatic rebuild is triggered:

```
Build Warning: Layout 'theme:components/hero-unit' requested in _hero_unit/intro.md does not exist.
```

The initial build works without any issue.

**Comment by imathis** [comment]
Interesting. Could you post a minimal rake task and any steps which I can use to reproduce this issue?

**Comment by mdotasia** [comment]
Clone https://github.com/UNStats/UNStats-theme/. Execute `bundle`, then `bundle exec rake test:preview`. First time it should work fine. Then change something in `test/source/index.html` to trigger rebuild. Then you should see errors.

**Comment by imathis** [comment]
Thanks. I'm following up on this now. I added a site reset hook to Octopress Hooks so I can clear out instance variables and rebuild plugins each time Jekyll triggers a build. I really appreciate your help.

**Comment by imathis** [comment]
I think we're good. I integrated with the new Octopress Hooks and now the plugins should all be reset for each build. I was able to get your repo to build changes without error with the new version, but let me know if this issue persists.

**Comment by mdotasia** [comment]
Looks good! Thanks for fixing.
