### ISSUE TITLE
Gem must be in both :jekyll_plugins and :octopress to work

### ISSUE THREAD

**Issue by skroll** [octopress/ink#28]
When using an ink plugin via a gem in a site, if it's not in both the :octopress and :jekyll_plugins then it cannot be used in both jekyll and ink.

For example:
```
group :jekyll_plugins do
  gem 'my-ink-plugin'
end
```
will cause the plugin to work in jekyll, but you cannot access it with `octopress ink list`.

In
```
group :octopress do
  gem 'my-ink-plugin'
end
```
then the plugin will show up in `octopress ink list` but it won't be used when the site is built with `jekyll build`. Of course you can always do:

```
group :jekyll_plugins, :octopress do
  gem 'my-ink-plugin'
end
```
but that seems to be a bit janky.

**Comment by imathis** [comment]
This should definitely be resolved now. Octopress now uses Jekyll's plugin manager to require plugins. There's no longer an `:octopress` group. The `:jekyll_plugins` group should work fine.
