### ISSUE TITLE
Compress javascripts independently and cache compiled js

### ISSUE THREAD

**Issue by imathis** [octopress/ink#34]
- [x] Javascripts should be compressed and cached individually; then combined. 
- [x] <s>By default, plugins should sort their own javascripts with `.min.js` at the top, and then sort by path.</s> Nah, I'd rather make ordering explicit.
- [ ] Allow explicit ordering of JS and CSS asset files in plugin configurations.

**Comment by oflannabhra** [comment]
Similar to this, would it be possible to define the order javascripts are compiled in other than using the path?

**Comment by imathis** [comment]
I should probably add something like this, though they would be localized to a specific plugin, of course.

**Comment by oflannabhra** [comment]
:+1:
