### ISSUE TITLE
Using Sass framework like Bourbon or Neat in ink plugin

### ISSUE THREAD

**Issue by mdotasia** [octopress/ink#35]
I would like to use Sass frameworks Bourbon and Neat in an Octopress Ink plugin. I copied Sass files to
- `assets/stylesheets/bourbon`
- `assets/styelsheets/neat`

I have a `styles.scss` in `assets/stylesheets` in which I do `@import 'bourbon/bourbon`. When I do a `jekyll build` I get an error that files from within the `bourbon` or `neat` directories are note found.

Do I have to add subdirectories to the load path and if yes how?

**Comment by imathis** [comment]
I haven't tried working with Bourbon yet. Did you add the proper gem requirements in your gemspec? If you want to post the source somewhere I'd be happy to help you troubleshoot.

**Comment by imathis** [comment]
Oh, I should mention, unless you're using vanilla Sass, I recommend adding pre-built stylesheets to your plugin. It just simplifies things for users and they don't have to deal with potential issues with extra dependencies.

**Comment by mdotasia** [comment]
Check https://github.com/UNStats/UNStats-theme/tree/plugin. `assets/stylesheets` contains the Sass files. It looks like files in sub-folders are a problem.

**Comment by mdotasia** [comment]
It looks like the `theme_load_path` is `assets/stylesheets` only without sub-directories. If Sass file is not found in there, `ink` looks in `user_load_path` in `_plugins` directory. Is there any reason why you do not add sub-directories in `assets/stylesheets`?

**Comment by mdotasia** [comment]
Fixed with #36.
