### ISSUE TITLE
Fonts copied to _site/plugin-slug/fonts/

### ISSUE THREAD

**Issue by oflannabhra** [octopress/ink#45]
Not sure if this was intended or not. I'm not familiar enough with clash to write a test for this, but font's are currently being copied into `_site/plugin-slug/fonts` instead of `_site/fonts/plugin-slug/` as referenced in the [docs](https://github.com/octopress/ink/blob/master/assets/docs/creating-a-plugin.markdown#plugin-assets). I can whip up a PR for either changing it to import to `_site/fonts/plugin-slug/` or a PR on the docs.

**Comment by imathis** [comment]
Thanks for posting this issue! I found that this was also affecting images. I've patched this and will be releasing a new version soon.
