### ISSUE TITLE
Pagination with theme gem

### ISSUE THREAD

**Issue by grantbachman** [octopress/ink#46]
I'm working on a theme gem for Octopress 3 and I'm having trouble getting Jekyll to generate paginated pages from the index.html inside the gem. Has anyone else had issues with this?

Things I've noticed:
- If no pagination is required (i.e. no page2 gets created), it doesn't show it's head
- If pagination *is* required, it throws the following error, once for every paginated page it's trying to create (excluding the first):
  - `Error reading file /path/to/gem/test/index.html: No such file or directory @ rb_sysopen - /path/to/myGem/test/index.html`
- If I move the index.html from `../myGem/assets/pages/` to `../myGem/test/` it paginates everything correctly.
  - I'm trying to avoid making someone copy code from my repo to get the gem working correctly, so I don't really see this as a solution.

I'm looking at the Genesis Theme and I can't find anything egregiously wrong with what I'm doing. Does anyone have any insights?
[Link to my code.](https://github.com/grantbachman/boldandblue)

**Comment by imathis** [comment]
@grantbachman Currently there is [no way to get Jekyll pagination to work](https://github.com/octopress/ink/pull/23) with Octopress Ink plugins. I'm working on an alternate solution that doesn't use the Jekyll paginate plugin.

**Comment by drallgood** [comment]
Jekyll's pagination is broken anyway. It only really works with the index page and assumes a lot.
I've been fighting with it for months...
+1 for creating our own plugin.

**Comment by grantbachman** [comment]
Thanks @imathis! Glad to know I'm not crazy :) Keep up the good work with this, Octopress 3 is turning out awesome!

**Comment by imathis** [comment]
I'm working on pagination here: [octopress-paginate](https://github.com/octopress/paginate). So far it's working pretty well. It's not ready to be used yet, but soon I think we'll be able to have pagination.
