### ISSUE TITLE
Plugin not registering; registered plugin not enabled

### ISSUE THREAD

**Issue by dznz** [octopress/ink#50]
I'm having trouble getting Ink working. I have been trying to install a couple of plugins and it is not working out for me.

```ruby
# Gemfile
...
gem 'octopress-ink'

group :octopress do
  gem 'octopress-codefence'
  gem 'octopress-solarized'
end
```

Then added the following lines to `_config.yml` (wasn't sure if they were still needed, but codefense started working when I added them)

```yaml
gems:
  - octopress-codefence
  - octopress-solarized
```

When I run Ink, I see that it knows about solarized, but not codefence.
```sh
$ bundle exec octopress ink list
Octopress Ink - v1.0.0.rc.56
 Octopress Solarized (octopress-solarized) - v1.0.3
Style code snippets with Ethan Schoonover's Solarized theme (tweaked a bit).
```

However, only codefence appears to actually be enabled on the site:
![Block of code with codefence but no solarized](https://cloud.githubusercontent.com/assets/245206/6772449/166b09be-d163-11e4-8c97-20883ffb20eb.png)

So at this point I'm guessing that the codefense plugin doesn't work within Ink, and that somehow Ink is not being used in my site. Am I doing something foolish here?

**Comment by imathis** [comment]
Hi @dznz Thanks for posting about this. A couple of things:

1. If you add plugins under `:jekyll_plugins` group, they'll be required automatically and you won't need to add them to your config file. I've stopped using the `:octopress`.
2. Octopress Codefence doesn't use Ink and therefor it won't show up in the list of Ink plugins.

Have you added `{% css_asset_tag %}` to your site's layout? That will add the stylesheets for Octopress solarized.

**Comment by dznz** [comment]
Cool, that explains it. If I get time, I'll put together PRs to update the docs.
