### ISSUE TITLE
List of thirdparty octopress 3 plugins?

### ISSUE THREAD

**Issue by ajesler** [octopress/ink#52]
Hi,

I have created a plugin for creating captioned images under octopress 3. It was mostly done as a learning experience, but on the off chance its useful to anyone else, is there a page I can add it to?

The plugin is  [octopress-captioned-image](https://github.com/ajesler/octopress-captioned-image).

Also, is there any objection to my publishing the gem with the `octopress-` prefix? Are you trying to reserve this for core octopress gems?

I'm also working on a gem for converting jekyll themes to octopress ink themes, but that is proving rather more complex. Will likely end up being more of a helper, requiring dev to tweak the output, especially where theme config files are concerned.

Thanks for all the great work on octopress 2 and looking forward to the release of v3.

**Comment by imathis** [comment]
Hi @ajesler. Thanks for posting this. I don't have a page for this yet but it would probably be a good idea to create a wiki on the octopress repo with a list of plugins. I'll set something up at the release.

That's a good question about the gem prefix. I think initially I expected that this would just be something I would use to mark things I'm building. It hadn't occurred to me (for some reason) that others would want to use it to signify that their plugins work with Octopress. The only concern that I have is that 3rd party plugins are obviously marked as such. GitHub makes it easy with user name-spaced repositories, but with ruby gems, that doesn't exist. There's not much I can do about that and the only real downside is that I don't get a name I want if someone else already has it. That's not too big a deal though.

If you have trouble getting an Ink theme to work, post an issue and ping me. I'm happy to help and I'm excited to see you're working on stuff. Thanks!

**Comment by ajesler** [comment]
Would the prefix `octopress-contrib-` be acceptable? I think that is easy to see that the gem is for octopress and it is not official. The `contrib` prefix is used by other projects to denote an unofficial extension so should not be completely foreign to devs.

**Comment by oflannabhra** [comment]
Why not just use `octo-` for 3rd party and `octopress-` for first party?

**Comment by ajesler** [comment]
That is a much better idea.

**Comment by imathis** [comment]
I was just thinking about this independently arrived at the same conclusion as @oflannabhra. Totally, use `octo-` as a prefix if you like.
