### ISSUE TITLE
Ink pulling in backup .scss~ files

### ISSUE THREAD

**Issue by dougbeal** [octopress/ink#57]
I'm porting a bootstrap theme to Ink, so I have the gem set to a local path.  This resulted in Ink picking up an Emacs backup of a .scss file.
[29] pry(Octopress::Ink::PluginAssetPipeline)> stylesheets['all'].map {|f| f.file }
=> ["grayscale-sass-ink.scss", "theme.scss~"]

**Comment by imathis** [comment]
Hmm. Emacs polluting the filesystem like that is annoying. I think there should be a more general way to avoid pulling in unintentional files than matching those specific characters. What is the `#` for?
